variable "name_prefix" {
  description = "Prefix for resource names, e.g. shiftmind-portfolio."
  type        = string
}

variable "environment" {
  description = "Environment name; log groups are /shiftmind/<environment>/<service>."
  type        = string
}

variable "region" {
  description = "AWS region (the awslogs driver's region)."
  type        = string
}

variable "secret_path_prefix" {
  description = "Secrets Manager name prefix, e.g. shiftmind/portfolio."
  type        = string
}

variable "database_url_secret_arn" {
  description = "ARN of the database-url secret (modules/data)."
  type        = string
}

variable "provisioning_database_url_secret_arn" {
  description = "ARN of the provisioning-database-url secret (modules/data)."
  type        = string
}

variable "oidc_client_secret" {
  description = "Cognito app client secret (modules/identity). Already in state per Story 6.1 D6, so it is stored as a plain secret_string."
  type        = string
  sensitive   = true
}

variable "csrf_secret" {
  description = "CSRF_SECRET, generated by the env root's ephemeral resource. Ephemeral."
  type        = string
  ephemeral   = true
  sensitive   = true
}

variable "credentials_version" {
  description = "Bump to rewrite the csrf-secret with a fresh ephemeral value."
  type        = number
}

variable "backend_image_digest" {
  description = "sha256 digest of the backend image to run. Null until the first image is pushed; then the migrate task definition is created."
  type        = string
  default     = null

  validation {
    condition     = var.backend_image_digest == null || can(regex("^sha256:[0-9a-f]{64}$", var.backend_image_digest))
    error_message = "backend_image_digest must be sha256:<64 lowercase hex> (an image digest, never a tag)."
  }
}

variable "planner_subject" {
  description = "SHIFTMIND_SEED_PLANNER_SUBJECT: the planner's Cognito sub."
  type        = string
}

variable "planner_email" {
  description = "SHIFTMIND_SEED_PLANNER_EMAIL."
  type        = string
}
