variable "region" {
  description = "AWS region of everything except the CloudFront certificate. ap-southeast-1 is closest to the site's Asia/Ho_Chi_Minh timezone and supports CloudFront VPC origins."
  type        = string
  default     = "ap-southeast-1"
}

variable "environment" {
  description = "Environment name; part of every resource name (shiftmind-<environment>) and the Environment tag."
  type        = string
  default     = "portfolio"
}

variable "availability_zones" {
  description = "Exactly two AZs. Null means the first two AZs of the region (<region>a, <region>b); set it to avoid an AZ that CloudFront VPC origins do not support."
  type        = list(string)
  default     = null
}

variable "vpc_cidr" {
  description = "CIDR of the VPC; must be a /16."
  type        = string
  default     = "10.20.0.0/16"
}

variable "hosted_zone_name" {
  description = "Name of an EXISTING public Route 53 hosted zone, e.g. example.com. Registering the domain and creating the zone are prerequisites (docs/AWS-RUNBOOK.md), not Terraform resources."
  type        = string
}

variable "app_domain" {
  description = "Public hostname of the app inside the hosted zone, e.g. shiftmind.example.com."
  type        = string

  validation {
    condition     = can(regex("^([a-z0-9]([a-z0-9-]*[a-z0-9])?\\.)+[a-z]{2,}$", var.app_domain))
    error_message = "app_domain must be a lowercase DNS name such as shiftmind.example.com."
  }
}

variable "cognito_domain_prefix" {
  description = "Prefix of the Cognito hosted-login domain; globally unique per region."
  type        = string
}

variable "planner_email" {
  description = "Email of the one planner user. Cognito mails the temporary password here."
  type        = string
}

# --- Story 6.2: data and runtime -------------------------------------------

variable "db_instance_class" {
  description = "RDS instance class (D5: db.t4g.micro when orderable for postgres 18.4 in the region, else db.t3.micro)."
  type        = string
}

variable "force_ssl_apply_method" {
  description = "apply_method for rds.force_ssl, as the postgres18 engine defaults report it."
  type        = string
  default     = "immediate"
}

variable "db_credentials_version" {
  description = "Bump to rewrite the master password, both database URL secrets and the CSRF secret with fresh ephemeral values."
  type        = number
  default     = 1
}

variable "backend_image_digest" {
  description = "sha256 digest of the backend image the migrate task runs. Null until the first image is pushed."
  type        = string
  default     = null
}

variable "github_repository" {
  description = "owner/name of this repository; the only one whose `portfolio` environment may assume the deploy role."
  type        = string
}

variable "github_environment" {
  description = "GitHub environment allowed to assume the deploy role."
  type        = string
  default     = "portfolio"
}

variable "github_oidc_provider_arn" {
  description = "ARN of an existing GitHub OIDC provider in the account; null creates one."
  type        = string
  default     = null
}

variable "monthly_budget_usd" {
  description = "Account-wide monthly cost budget in USD."
  type        = number

  validation {
    condition     = var.monthly_budget_usd > 0
    error_message = "monthly_budget_usd must be positive."
  }
}

variable "budget_alert_email" {
  description = "Where the budget's 80% actual and 100% forecasted alerts go."
  type        = string
}

# Generated by the env root's ephemeral resources (D6). Ephemeral: in neither
# state nor a plan file. Tests set them to literals.
variable "migrator_password" {
  description = "RDS master (shiftmind_migrator) password. Ephemeral."
  type        = string
  ephemeral   = true
  sensitive   = true
}

variable "login_password" {
  description = "shiftmind_login password. Ephemeral."
  type        = string
  ephemeral   = true
  sensitive   = true
}

variable "csrf_secret" {
  description = "CSRF_SECRET. Ephemeral."
  type        = string
  ephemeral   = true
  sensitive   = true
}
