/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fixtures */
        get: operations["list_fixtures_fixtures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario Overrides */
        get: operations["get_scenario_overrides_scenarios__scenario_id__overrides_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_scenarios__scenario_id__runs_get"];
        put?: never;
        /** Trigger Run */
        post: operations["trigger_run_scenarios__scenario_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Result */
        get: operations["get_run_result_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Insights
         * @description Return or generate a plain-language insight report for a completed run.
         *
         *     Declaring as sync `def` (not async) runs this handler in FastAPI's anyio
         *     threadpool — off the event loop and entirely separate from the single-worker
         *     solve pool (D-02).  No new executor is added.
         *
         *     200 + ready=true  — report available (generated fresh or returned from cache)
         *     200 + ready=false — run not yet COMPLETED (D-07; deliberate 200, not 409)
         *     404               — unknown run_id
         *     502               — provider failure or D-06 grounding guard rejection (D-08)
         */
        get: operations["get_run_insights_runs__run_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Constraint */
        post: operations["parse_constraint_constraints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fixture Versions */
        get: operations["list_fixture_versions_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario Context */
        get: operations["get_scenario_context_api_v1_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projection */
        get: operations["get_projection_api_v1_scenarios__scenario_id__projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/work-areas-and-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tasks */
        get: operations["get_tasks_api_v1_scenarios__scenario_id__projection_work_areas_and_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workers */
        get: operations["get_workers_api_v1_scenarios__scenario_id__projection_workers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demand */
        get: operations["get_demand_api_v1_scenarios__scenario_id__projection_demand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/baseline-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Baseline Assignments */
        get: operations["get_baseline_assignments_api_v1_scenarios__scenario_id__projection_baseline_assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Locks */
        get: operations["get_locks_api_v1_scenarios__scenario_id__projection_locks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/constraints-and-objectives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Constraints */
        get: operations["get_constraints_api_v1_scenarios__scenario_id__projection_constraints_and_objectives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/work-areas-and-tasks/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Task */
        get: operations["resolve_task_api_v1_scenarios__scenario_id__projection_work_areas_and_tasks__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/workers/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Worker */
        get: operations["resolve_worker_api_v1_scenarios__scenario_id__projection_workers__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/demand/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Demand Interval */
        get: operations["resolve_demand_interval_api_v1_scenarios__scenario_id__projection_demand__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/baseline-assignments/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Assignment */
        get: operations["resolve_assignment_api_v1_scenarios__scenario_id__projection_baseline_assignments__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/locks/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Lock */
        get: operations["resolve_lock_api_v1_scenarios__scenario_id__projection_locks__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/projection/constraints-and-objectives/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Constraint */
        get: operations["resolve_constraint_api_v1_scenarios__scenario_id__projection_constraints_and_objectives__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_v1_conversations__conversation_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conversation Events
         * @description Replay and follow one conversation's persisted event stream (AD-21).
         *
         *     Note what this route does **not** depend on: `get_site_context`. That
         *     dependency holds one pooled connection inside an open transaction for the
         *     whole request, which is correct for a 40 ms read and an outage for a stream
         *     that lives for hours. The stream opens a short transaction per poll instead.
         */
        get: operations["conversation_events_api_v1_conversations__conversation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptedTurnOut */
        AcceptedTurnOut: {
            activity: components["schemas"]["ActivityItemOut"];
            /** Resource Version */
            resource_version: number;
            /** Agent Run Status */
            agent_run_status: string;
            /** Sequence */
            sequence: string;
        };
        /** ActivityItemOut */
        ActivityItemOut: {
            /** Schema Version */
            schema_version: string;
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Activity Type
             * @enum {string}
             */
            activity_type: "planner_message" | "agent_response" | "clarification" | "draft" | "run_progress" | "comparison" | "approval_request" | "terminal_outcome";
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Conversation Resource Version */
            conversation_resource_version: number;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Text */
            text: string;
            /** Sequence */
            sequence: string;
        };
        /** AppliedConstraint */
        AppliedConstraint: {
            /** Id */
            id: string;
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Parsed Constraint */
            parsed_constraint: string;
        };
        /** AssignmentOut */
        AssignmentOut: {
            /** Record Id */
            record_id: string;
            /** Worker Id */
            worker_id: string;
            /** Task Id */
            task_id: string;
            /** Shift Id */
            shift_id: string | null;
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
        };
        /** AssignmentPageOut */
        AssignmentPageOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Group
             * @constant
             */
            group: "baseline-assignments";
            /** Items */
            items: components["schemas"]["AssignmentOut"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Total Count */
            total_count: number;
            /** Matching Count */
            matching_count: number;
        };
        /** AuthSessionOut */
        AuthSessionOut: {
            /**
             * App User Id
             * Format: uuid
             */
            app_user_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** AvailabilityWindowOut */
        AvailabilityWindowOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "roster" | "availability";
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
        };
        /** ConstraintPageOut */
        ConstraintPageOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Group
             * @constant
             */
            group: "constraints-and-objectives";
            /** Items */
            items: components["schemas"]["ConstraintProjectionOut"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Total Count */
            total_count: number;
            /** Matching Count */
            matching_count: number;
        };
        /** ConstraintParseRequest */
        ConstraintParseRequest: {
            /** Scenario Id */
            scenario_id: string;
            /** Text */
            text: string;
        };
        /** ConstraintParseResponse */
        ConstraintParseResponse: {
            /** Applied */
            applied: components["schemas"]["AppliedConstraint"][];
            /** Rejected */
            rejected: components["schemas"]["RejectedConstraint"][];
            /** Clarification Needed */
            clarification_needed: string | null;
            /** No Constraint Found */
            no_constraint_found: boolean;
        };
        /** ConstraintProjectionOut */
        ConstraintProjectionOut: {
            /** Record Id */
            record_id: string;
            /** Constraint Type */
            constraint_type: string;
            /** Value */
            value: string;
            /** Value Type */
            value_type: string | null;
        };
        /** ConversationCreateIn */
        ConversationCreateIn: {
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
        };
        /** ConversationListOut */
        ConversationListOut: {
            /** Items */
            items: components["schemas"]["ConversationOut"][];
            /** Limit */
            limit: number;
            /** Has More */
            has_more: boolean;
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /** Resource Version */
            resource_version: number;
        };
        /** DemandIntervalOut */
        DemandIntervalOut: {
            /** Record Id */
            record_id: string;
            /**
             * Family
             * @enum {string}
             */
            family: "outbound" | "inbound" | "indirect";
            /** Task Id */
            task_id: string;
            /** Area Id */
            area_id: string | null;
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
            /** Amount */
            amount: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "volume" | "headcount";
        };
        /** DemandIntervalPageOut */
        DemandIntervalPageOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Group
             * @constant
             */
            group: "demand";
            /** Items */
            items: components["schemas"]["DemandIntervalOut"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Total Count */
            total_count: number;
            /** Matching Count */
            matching_count: number;
        };
        /** FixtureCatalogueEntryOut */
        FixtureCatalogueEntryOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /** Fixture Id */
            fixture_id: string;
            /** Scenario Name */
            scenario_name: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /** Fixture Version */
            fixture_version: string;
            /** Checksum Algorithm */
            checksum_algorithm: string;
            /** Checksum Schema Version */
            checksum_schema_version: string;
            /** Checksum Digest */
            checksum_digest: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightOut */
        InsightOut: {
            /** Ready */
            ready: boolean;
            /** Run Id */
            run_id: string;
            /** Report */
            report?: string | null;
            /** Status */
            status?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** LockOut */
        LockOut: {
            /** Record Id */
            record_id: string;
            /** Target Type */
            target_type: string;
            /** Target Ref */
            target_ref: string;
            /** Scope */
            scope: string;
            /** Source */
            source: string;
        };
        /** LockPageOut */
        LockPageOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Group
             * @constant
             */
            group: "locks";
            /** Items */
            items: components["schemas"]["LockOut"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Total Count */
            total_count: number;
            /** Matching Count */
            matching_count: number;
        };
        /** MessageCreateIn */
        MessageCreateIn: {
            /** Text */
            text: string;
        };
        /** OverrideOut */
        OverrideOut: {
            /** Id */
            id: string;
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Parsed Constraint */
            parsed_constraint?: string | null;
        };
        /** ProblemDetailsV1 */
        ProblemDetailsV1: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
        };
        /** QualificationRefOut */
        QualificationRefOut: {
            /** Task Id */
            task_id: string;
            /** Rate */
            rate: number;
        };
        /** RejectedConstraint */
        RejectedConstraint: {
            /** Tool */
            tool: string;
            /** Error */
            error: string;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Solver Status */
            solver_status?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ScenarioContextOut */
        ScenarioContextOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /** Scenario Name */
            scenario_name: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /** Fixture Version */
            fixture_version: string;
            /** Checksum Algorithm */
            checksum_algorithm: string;
            /** Checksum Schema Version */
            checksum_schema_version: string;
            /** Checksum Digest */
            checksum_digest: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Baseline Schedule Version */
            baseline_schedule_version: string | null;
        };
        /** ScenarioCreate */
        ScenarioCreate: {
            /** Name */
            name: string;
            /** Fixture */
            fixture: string;
            /**
             * Time Limit S
             * @default 60
             */
            time_limit_s: number;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Fixture */
            fixture: string;
            /** Time Limit S */
            time_limit_s: number;
            /** Created At */
            created_at: string;
        };
        /** ScenarioOverviewOut */
        ScenarioOverviewOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Fixture Id */
            fixture_id: string;
            /** Scenario Name */
            scenario_name: string;
            /** Fixture Version */
            fixture_version: string;
            /** Checksum Algorithm */
            checksum_algorithm: string;
            /** Checksum Schema Version */
            checksum_schema_version: string;
            /** Checksum Digest */
            checksum_digest: string;
            /**
             * Horizon Start
             * Format: date-time
             */
            horizon_start: string;
            /** Site Timezone */
            site_timezone: string;
            /** Horizon Minutes */
            horizon_minutes: number;
            /** Baseline Schedule Version */
            baseline_schedule_version: string | null;
            /**
             * Projection Generated At
             * Format: date-time
             */
            projection_generated_at: string;
            /** Work Area Count */
            work_area_count: number;
            /** Task Count */
            task_count: number;
            /** Worker Count */
            worker_count: number;
            /** Demand Interval Count */
            demand_interval_count: number;
            /** Baseline Assignment Count */
            baseline_assignment_count: number;
            /** Lock Count */
            lock_count: number;
            /** Constraint Count */
            constraint_count: number;
        };
        /** TaskPageOut */
        TaskPageOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Group
             * @constant
             */
            group: "work-areas-and-tasks";
            /** Items */
            items: components["schemas"]["TaskProjectionOut"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Total Count */
            total_count: number;
            /** Matching Count */
            matching_count: number;
        };
        /** TaskProjectionOut */
        TaskProjectionOut: {
            /** Record Id */
            record_id: string;
            /** Task Id */
            task_id: string;
            /** Name */
            name: string;
            /** Function */
            function: string;
            /** Area Id */
            area_id: string;
            /** Area Name */
            area_name: string;
            /** Unit Type Id */
            unit_type_id: string | null;
        };
        /** TimelineOut */
        TimelineOut: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Resource Version */
            resource_version: number;
            /** Latest Agent Run Status */
            latest_agent_run_status: string | null;
            /** Items */
            items: components["schemas"]["ActivityItemOut"][];
            /** Limit */
            limit: number;
            /** Has More */
            has_more: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerPageOut */
        WorkerPageOut: {
            /**
             * Schema Version
             * @default v1
             */
            schema_version: string;
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Scenario Version Id
             * Format: uuid
             */
            scenario_version_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Group
             * @constant
             */
            group: "workers";
            /** Items */
            items: components["schemas"]["WorkerProjectionOut"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Total Count */
            total_count: number;
            /** Matching Count */
            matching_count: number;
        };
        /** WorkerProjectionOut */
        WorkerProjectionOut: {
            /** Record Id */
            record_id: string;
            /** Contact Id */
            contact_id: string;
            /** Name */
            name: string;
            /** Employment Type */
            employment_type: string;
            /** Grade */
            grade: string;
            /** Eba */
            eba: string;
            /** Contracted Hours */
            contracted_hours: number;
            /** Qualifications */
            qualifications: components["schemas"]["QualificationRefOut"][];
            /** Availability Windows */
            availability_windows: components["schemas"]["AvailabilityWindowOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_fixtures_fixtures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    create_scenario_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"];
                };
            };
            /** @description Unknown fixture */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"];
                };
            };
            /** @description Scenario not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_overrides_scenarios__scenario_id__overrides_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideOut"][];
                };
            };
            /** @description Scenario not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_scenarios__scenario_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_scenarios__scenario_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Scenario not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_result_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run not completed yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_insights_runs__run_id__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightOut"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Insight generation failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    parse_constraint_constraints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintParseResponse"];
                };
            };
            /** @description Scenario not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description LLM provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_v1_auth_login_get: {
        parameters: {
            query?: {
                return_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the configured OIDC provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    callback_api_v1_auth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application session created */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    list_fixture_versions_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureCatalogueEntryOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    get_scenario_context_api_v1_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioContextOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projection_api_v1_scenarios__scenario_id__projection_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOverviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    get_tasks_api_v1_scenarios__scenario_id__projection_work_areas_and_tasks_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                sort?: ("task_id" | "name" | "function" | "area_id" | "area_name") | null;
                order?: "asc" | "desc";
                task_id?: string | null;
                name_contains?: string | null;
                function?: string | null;
                area_id?: string | null;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPageOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    get_workers_api_v1_scenarios__scenario_id__projection_workers_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                sort?: ("contact_id" | "name" | "employment_type" | "grade" | "contracted_hours") | null;
                order?: "asc" | "desc";
                contact_id?: string | null;
                name_contains?: string | null;
                employment_type?: string | null;
                grade?: string | null;
                qualified_task_id?: string | null;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPageOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    get_demand_api_v1_scenarios__scenario_id__projection_demand_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                sort?: ("start_minute" | "end_minute" | "task_id" | "family" | "amount") | null;
                order?: "asc" | "desc";
                family?: ("outbound" | "inbound" | "indirect") | null;
                task_id?: string | null;
                area_id?: string | null;
                start_minute_gte?: number | null;
                end_minute_lte?: number | null;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemandIntervalPageOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    get_baseline_assignments_api_v1_scenarios__scenario_id__projection_baseline_assignments_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                sort?: ("start_minute" | "worker_id" | "task_id") | null;
                order?: "asc" | "desc";
                worker_id?: string | null;
                task_id?: string | null;
                shift_id?: string | null;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentPageOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    get_locks_api_v1_scenarios__scenario_id__projection_locks_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                sort?: ("target_type" | "target_ref" | "scope" | "source") | null;
                order?: "asc" | "desc";
                target_type?: string | null;
                target_ref?: string | null;
                scope?: string | null;
                source?: string | null;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockPageOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    get_constraints_api_v1_scenarios__scenario_id__projection_constraints_and_objectives_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                sort?: ("constraint_type" | "value_type") | null;
                order?: "asc" | "desc";
                constraint_type?: string | null;
                value_type?: string | null;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintPageOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    resolve_task_api_v1_scenarios__scenario_id__projection_work_areas_and_tasks__record_id__get: {
        parameters: {
            query: {
                scenario_version_id: string;
            };
            header?: never;
            path: {
                scenario_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskProjectionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    resolve_worker_api_v1_scenarios__scenario_id__projection_workers__record_id__get: {
        parameters: {
            query: {
                scenario_version_id: string;
            };
            header?: never;
            path: {
                scenario_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerProjectionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    resolve_demand_interval_api_v1_scenarios__scenario_id__projection_demand__record_id__get: {
        parameters: {
            query: {
                scenario_version_id: string;
            };
            header?: never;
            path: {
                scenario_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemandIntervalOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    resolve_assignment_api_v1_scenarios__scenario_id__projection_baseline_assignments__record_id__get: {
        parameters: {
            query: {
                scenario_version_id: string;
            };
            header?: never;
            path: {
                scenario_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    resolve_lock_api_v1_scenarios__scenario_id__projection_locks__record_id__get: {
        parameters: {
            query: {
                scenario_version_id: string;
            };
            header?: never;
            path: {
                scenario_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    resolve_constraint_api_v1_scenarios__scenario_id__projection_constraints_and_objectives__record_id__get: {
        parameters: {
            query: {
                scenario_version_id: string;
            };
            header?: never;
            path: {
                scenario_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintProjectionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query: {
                scenario_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    send_message_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedTurnOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    timeline_api_v1_conversations__conversation_id__timeline_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
    conversation_events_api_v1_conversations__conversation_id__events_get: {
        parameters: {
            query?: {
                last_event_id?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream of persisted conversation activity. Each frame is `id: <stream_uuid>:<sequence>`, `event: <event_type>`, `data: <ActivityItemOut as compact JSON>`; comment-only heartbeats carry no id and are never persisted (AD-21). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ProblemDetailsV1"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ProblemDetailsV1"];
                };
            };
        };
    };
}
