variable "name_prefix" {
  description = "Prefix for resource names, e.g. shiftmind-portfolio."
  type        = string
}

variable "secret_path_prefix" {
  description = "Secrets Manager name prefix, e.g. shiftmind/portfolio (secrets are <prefix>/<name>)."
  type        = string
}

variable "data_subnet_ids" {
  description = "Private data subnet IDs (Story 6.1 network module); the DB subnet group is exactly these."
  type        = list(string)

  validation {
    condition     = length(var.data_subnet_ids) >= 2
    error_message = "An RDS subnet group needs subnets in at least two AZs."
  }
}

variable "data_security_group_id" {
  description = "The data-tier security group; the instance's only security group."
  type        = string
}

variable "db_instance_class" {
  description = "RDS instance class (Story 6.2 D5: db.t4g.micro when orderable for 18.4 in the region)."
  type        = string
}

variable "force_ssl_apply_method" {
  description = "apply_method for rds.force_ssl. 1 is the postgres18 default, so AWS keeps it as a system value and reports pending-reboot; immediate would show as a change on every plan."
  type        = string
  default     = "pending-reboot"

  validation {
    condition     = contains(["immediate", "pending-reboot"], var.force_ssl_apply_method)
    error_message = "apply_method is immediate or pending-reboot."
  }
}

# D6: generated by the env root's ephemeral resources. Ephemeral, so they are
# in neither state nor a plan file; they reach AWS only through write-only
# arguments.
variable "migrator_password" {
  description = "Master (shiftmind_migrator) password. Ephemeral."
  type        = string
  ephemeral   = true
  sensitive   = true
}

variable "login_password" {
  description = "shiftmind_login password, written into the database-url secret. Ephemeral."
  type        = string
  ephemeral   = true
  sensitive   = true
}

variable "db_credentials_version" {
  description = "Bump to rewrite the master password and both URL secrets with fresh ephemeral values."
  type        = number
}
